Add cyrillic code
rofafor/vdr-plugin-osdteletext pull request #3
Opened 2018-01-29 13:21 UTC by ua0lnj

Updated. I understand you correctly?

2018-01-29 14:57 UTC, rofafor requested changes
Just make the requested changes into this same PR.

2018-01-29 14:57 UTC, rofafor commented on osdteletext.c
> +   Add(new cMenuEditStraItem(tr("G2 code block"), &temp.txtG2Block, 11, txtBlock));
Use a proper way to determinate the txtBlock length, for example: ```#define ELEMENTS(x) (sizeof(x) / sizeof(x[0]))```

2018-01-29 14:57 UTC, rofafor commented on osdteletext.c
> +//      tr("Reserved")  //0x0f
Let's remove these commented lines - they don't bring any additional information.

2018-01-29 14:57 UTC, rofafor commented on osdteletext.c
> +   static const char *txtBlock[] = {
Sorry about the misleading comment of previous PR. I had a proper look at the code and your original way to include this into ```temp``` was correct and, please, change it as it were.

2018-01-30 13:36 UTC, ua0lnj commented
What you think about this? :)
Add(new cMenuEditStraItem(tr("G0 code block"), &temp.txtG0Block, (&txtBlock)[1]-txtBlock), txtBlock));
Add(new cMenuEditStraItem(tr("G2 code block"), &temp.txtG2Block, (&txtBlock)[1]-txtBlock), txtBlock));
It's works.

2018-01-30 16:26 UTC, rofafor commented
Just use the standard way of ```sizeof(all) / sizeof(first element)````

2018-01-31 11:08 UTC, ua0lnj commented
Please, see now.

2018-01-31 20:42 UTC, rofafor commented
I made some generic tweaks, squashed everything into a one commit, and merged into the vdr-2.3.x branch.

2018-01-31 20:42 UTC, closed without merging